---
- name: execute script and get result back.
  hosts: 169.57.13.100
  
  tasks:
    - name: Recursively find /tmp files older than 1hour or 2 day or 4 weeks  
      find:
       paths: /var/log
       patterns: '*.log.gz'
       age: 3600
       #age: 2d
       #age: 4w
       recurse: yes
