---
- name: execute script and get result back.
  hosts: 169.57.13.100
  
  tasks:
    - name: Recursively find /.log files older than 1hour or 2 day or 4 weeks  
      find:
        paths: /var/log
        patterns: '*.log'
        size: 10m
       #age: 60
       #age: 3600
       #age: 2d
       #age: 4w
        #recurse: yes
      register: logdetails
       recurse: yes
     
    - name: Print the script result
      debug:
        msg: "{{ logdetails.stdout }}" 
